### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-hjfs#1]

**Comment by JoseABCruz** [comment]
[Informe de entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-hjfs/files/9465523/Informe.de.entrevista.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Informe de entrevista (Federico Victoriano Sierra (5US)).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-hjfs/files/9465527/Informe.de.entrevista.Federico.Victoriano.Sierra.5US.pdf)

**Comment by Heidi-19** [comment]
[Informe de entrevista - Heidi Lucy Bautista Sanjuan .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-hjfs/files/9465528/Informe.de.entrevista.-.Heidi.Lucy.Bautista.Sanjuan.pdf)

**Comment by abicoronel** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
